service: talonone-sheerid
frameworkVersion: '3'

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs18.x

functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-esbuild
